-- MySQL Script generated by MySQL Workbench
-- Sat Sep 12 14:00:53 2020
-- Model: Modelo ER TCC    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autoPark
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema autoPark
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autoPark` DEFAULT CHARACTER SET utf8 ;
USE `autoPark` ;

-- -----------------------------------------------------
-- Table `autoPark`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoPark`.`usuarios` (
  `cpf` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(35) NOT NULL,
  `perfil` TINYINT(1) NOT NULL COMMENT 'Perfil - conterá quais os possiveis (Administrador, Funcionario e Cliente)\nacesso - Indicação de primeiro acesso ou senha provisória, caso seja \"true\", deve solicitar a alteração.',
  `acesso` TINYINT(1) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoPark`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoPark`.`empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(14) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoPark`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoPark`.`funcionarios` (
  `idFuncionarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `usuarios_cpf` VARCHAR(11) NOT NULL,
  `empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idFuncionarios`),
  INDEX `fk_funcionarios_usuarios_idx` (`usuarios_cpf` ASC) ,
  INDEX `fk_funcionarios_empresa1_idx` (`empresa_idEmpresa` ASC) ,
  CONSTRAINT `fk_funcionarios_usuarios`
    FOREIGN KEY (`usuarios_cpf`)
    REFERENCES `autoPark`.`usuarios` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionarios_empresa1`
    FOREIGN KEY (`empresa_idEmpresa`)
    REFERENCES `autoPark`.`empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoPark`.`pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoPark`.`pagamentos` (
  `idPagamentos` INT NOT NULL AUTO_INCREMENT,
  `numeroCartao` INT NOT NULL,
  `nomeTitular` VARCHAR(45) NOT NULL,
  `validade` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idPagamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoPark`.`creditos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoPark`.`creditos` (
  `idCartaoCredito` INT NOT NULL AUTO_INCREMENT,
  `saldo` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idCartaoCredito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoPark`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoPark`.`marcas` (
  `idMarcas` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarcas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoPark`.`modelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoPark`.`modelos` (
  `idModelos` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `marcas_idMarcas` INT NOT NULL,
  PRIMARY KEY (`idModelos`),
  INDEX `fk_modelos_marcas1_idx` (`marcas_idMarcas` ASC) ,
  CONSTRAINT `fk_modelos_marcas1`
    FOREIGN KEY (`marcas_idMarcas`)
    REFERENCES `autoPark`.`marcas` (`idMarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoPark`.`tiposVeiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoPark`.`tiposVeiculos` (
  `idValores` INT NOT NULL AUTO_INCREMENT,
  `veiculo` VARCHAR(45) NOT NULL COMMENT 'Tipos de veiculos (Carro, Moto, Caminhonete)',
  PRIMARY KEY (`idValores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoPark`.`veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoPark`.`veiculos` (
  `idVeiculos` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(7) NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `ano` YEAR(4) NOT NULL,
  `modelos_idModelos` INT NOT NULL,
  `tiposVeiculos_idValores` INT NOT NULL,
  PRIMARY KEY (`idVeiculos`),
  INDEX `fk_veiculos_modelos1_idx` (`modelos_idModelos` ASC) ,
  INDEX `fk_veiculos_tiposVeiculos1_idx` (`tiposVeiculos_idValores` ASC) ,
  CONSTRAINT `fk_veiculos_modelos1`
    FOREIGN KEY (`modelos_idModelos`)
    REFERENCES `autoPark`.`modelos` (`idModelos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculos_tiposVeiculos1`
    FOREIGN KEY (`tiposVeiculos_idValores`)
    REFERENCES `autoPark`.`tiposVeiculos` (`idValores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoPark`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoPark`.`clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(11) NOT NULL,
  `celular` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `usuarios_cpf` VARCHAR(11) NOT NULL,
  `pagamentos_idPagamentos` INT NOT NULL,
  `creditos_idCartaoCredito` INT NOT NULL,
  `veiculos_idVeiculos` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_cliente_usuarios1_idx` (`usuarios_cpf` ASC) ,
  INDEX `fk_clientes_pagamentos1_idx` (`pagamentos_idPagamentos` ASC) ,
  INDEX `fk_clientes_creditos1_idx` (`creditos_idCartaoCredito` ASC) ,
  INDEX `fk_clientes_veiculos1_idx` (`veiculos_idVeiculos` ASC) ,
  CONSTRAINT `fk_cliente_usuarios1`
    FOREIGN KEY (`usuarios_cpf`)
    REFERENCES `autoPark`.`usuarios` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_pagamentos1`
    FOREIGN KEY (`pagamentos_idPagamentos`)
    REFERENCES `autoPark`.`pagamentos` (`idPagamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_creditos1`
    FOREIGN KEY (`creditos_idCartaoCredito`)
    REFERENCES `autoPark`.`creditos` (`idCartaoCredito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_veiculos1`
    FOREIGN KEY (`veiculos_idVeiculos`)
    REFERENCES `autoPark`.`veiculos` (`idVeiculos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoPark`.`estacionamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoPark`.`estacionamento` (
  `idEstacionamento` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(45) NOT NULL,
  `numeroVagas` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idEstacionamento`),
  INDEX `fk_estacionamento_empresa1_idx` (`empresa_idEmpresa` ASC) ,
  CONSTRAINT `fk_estacionamento_empresa1`
    FOREIGN KEY (`empresa_idEmpresa`)
    REFERENCES `autoPark`.`empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoPark`.`checkin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoPark`.`checkin` (
  `idCheckin` INT NOT NULL AUTO_INCREMENT,
  `dataHora` DATETIME NOT NULL,
  `estacionamento_idEstacionamento` INT NOT NULL,
  `clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCheckin`),
  INDEX `fk_checkin_estacionamento1_idx` (`estacionamento_idEstacionamento` ASC) ,
  INDEX `fk_checkin_clientes1_idx` (`clientes_idCliente` ASC) ,
  CONSTRAINT `fk_checkin_estacionamento1`
    FOREIGN KEY (`estacionamento_idEstacionamento`)
    REFERENCES `autoPark`.`estacionamento` (`idEstacionamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_checkin_clientes1`
    FOREIGN KEY (`clientes_idCliente`)
    REFERENCES `autoPark`.`clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoPark`.`checkout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoPark`.`checkout` (
  `idCheckout` INT NOT NULL AUTO_INCREMENT,
  `dataHora` DATETIME NOT NULL,
  `valorCobrado` DECIMAL(10,2) NOT NULL,
  `clientes_idCliente` INT NOT NULL,
  `estacionamento_idEstacionamento` INT NOT NULL,
  PRIMARY KEY (`idCheckout`),
  INDEX `fk_checkout_clientes1_idx` (`clientes_idCliente` ASC) ,
  INDEX `fk_checkout_estacionamento1_idx` (`estacionamento_idEstacionamento` ASC) ,
  CONSTRAINT `fk_checkout_clientes1`
    FOREIGN KEY (`clientes_idCliente`)
    REFERENCES `autoPark`.`clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_checkout_estacionamento1`
    FOREIGN KEY (`estacionamento_idEstacionamento`)
    REFERENCES `autoPark`.`estacionamento` (`idEstacionamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoPark`.`estacionamento_has_tiposVeiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoPark`.`estacionamento_has_tiposVeiculos` (
  `estacionamento_idEstacionamento` INT NOT NULL,
  `tiposVeiculos_idValores` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `tipoPlano` VARCHAR(45) NOT NULL COMMENT 'Anual\nMensal até alcançar o valor da Anual\nDiaria até alcançar o valor da Mensal\nHora até alcançar o valor da Diaria\n',
  PRIMARY KEY (`estacionamento_idEstacionamento`, `tiposVeiculos_idValores`),
  INDEX `fk_estacionamento_has_tiposVeiculos_tiposVeiculos1_idx` (`tiposVeiculos_idValores` ASC) ,
  INDEX `fk_estacionamento_has_tiposVeiculos_estacionamento1_idx` (`estacionamento_idEstacionamento` ASC) ,
  CONSTRAINT `fk_estacionamento_has_tiposVeiculos_estacionamento1`
    FOREIGN KEY (`estacionamento_idEstacionamento`)
    REFERENCES `autoPark`.`estacionamento` (`idEstacionamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estacionamento_has_tiposVeiculos_tiposVeiculos1`
    FOREIGN KEY (`tiposVeiculos_idValores`)
    REFERENCES `autoPark`.`tiposVeiculos` (`idValores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
